version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "9007:2181"
    networks:
      kafkaNetwork:
        ipv4_address: 10.10.20.141
  kafka:
    image: bitnami/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9008:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.20.142
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.1.42:9008
    networks:
      kafkaNetwork:
        ipv4_address: 10.10.20.142
networks:
  kafkaNetwork:
    external: true