version: '3'


services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8.0
    container_name: sb-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: smart_barricade
      MYSQL_ROOT_PASSWORD: sbroot1234
      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/data:/var/lib/mysql
#      - ./db/mysql/init:/docker-entrypoint-initdb.d
#    platform: linux/x86_64