version: '2'


services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=smartbarricade'
      - 'MYSQL_PASSWORD=sb1234!'
      - 'MYSQL_ROOT_PASSWORD=sb1234!'
      - 'MYSQL_USER=sbuser'
    ports:
      - '3306'